Models/ErrorViewModel.cs
namespace Task2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Task2.Models;

namespace Task2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TodoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Task2.DataModel;
using Task2.Dto;
using Task2.Interfaces;

namespace Task2.Controllers
{
    public class TodoController : Controller
    {
        private readonly ITodolistService _todolistService;
        private readonly IMapper _mapper;
        public TodoController(ITodolistService todolistService, IMapper mapper)
        {
            _todolistService = todolistService;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var result = _todolistService.Get();
            if (result == null) {
                return View("Error");
            }
           
            return View(_mapper.Map<IEnumerable<TodolistItemDto>>(result));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateTodolistItemDto createDto)
        {
            var newItem = _todolistService.Post(_mapper.Map<CreateTodolistItemDto, TodolistItem>(createDto));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var item = _todolistService.Get(id);
            if (item == null)
                return NotFound();
            return View(_mapper.Map<TodolistItem, TodolistItemDto>(item));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var item = _todolistService.Get(id);
            return View(_mapper.Map<TodolistItem,UpdateTodolistItemDto>(item));
        }

        public ActionResult Edit(UpdateTodolistItemDto updateDto)
        {
            var result = _todolistService.Put(_mapper.Map<UpdateTodolistItemDto, TodolistItem>(updateDto));
            return RedirectToAction("Index");
        }

        public ActionResult Delete([FromRoute]int id)
        {
            var result = _todolistService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">Список дел</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Task2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Todo/Create.cshtml
@model CreateTodolistItemDto

@{
	ViewData["Title"] = "Create";
}

@using (Html.BeginForm("Create", "Todo", FormMethod.Post))
{
    @Html.Label("Task Name");
    @Html.TextBoxFor(m => m.Title);
    @Html.Label("Status");
    @Html.CheckBoxFor(m => m.IsCompleted);
    <input type="submit" value="Create" />
}

Views/Todo/Details.cshtml
@model TodolistItemDto

@{
	ViewData["Title"] = "Details";
}

<div>
	<p>@Model.Title</p>
	<p>@Html.FormatBool(Model.IsCompleted)</p>
</div>

<a asp-action="Index">Back</a>

Views/Todo/Edit.cshtml
@model UpdateTodolistItemDto

@{
    ViewData["Title"] = "Edit";
}

@using (Html.BeginForm("Edit", "Todo", FormMethod.Post))
{
    @Html.HiddenFor(mbox=>mbox.Id);
    @Html.Label("Task Name");
    @Html.TextBoxFor(m => m.Title);
    @Html.Label("Status");
    @Html.CheckBoxFor(m => m.IsCompleted);
    <input type="submit" value="Edit" />
}

Views/Todo/Index.cshtml
@model IEnumerable<TodolistItemDto>

<h1>Todolist</h1>

<a asp-controller="Todo" asp-action="Create" class="btn btn btn-success">Create</a>
<table class="table table-responsive table-striped table-hover align-middle">
	<thead>
		<tr class="text-center">
			<th>Name</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr class="text-center">
				<td>@item.Title</td>
				<td>@Html.FormatBool(item.IsCompleted)</td>
				<td>
					<a asp-controller="Todo" asp-action="Details" asp-route-id="@item.Id" class="btn btn btn-success">Details</a>
					<a asp-controller="Todo" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
					<a asp-controller="Todo" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>